### ISSUE TITLE
下拉很卡

### ISSUE THREAD

**Issue by NeoPi** [greatbsky/react-native-pullview-demo#1]
如题，下拉的时候很卡。

**Comment by greatbsky** [comment]
组件内容尽量采用原生的组件，不要再套用第三方的组件，rn单线程运行，所以慢，等过一段时间我会考虑下如何优化下~~

**Comment by greatbsky** [comment]
这个问题跟https://github.com/greatbsky/react-native-pull/issues/4 同样的问题，所以将这个issue关了
